#!/usr/bin/env python3
"""Regenerates misc/tools/std_include_table.txt. Run only to refresh the pins below.

Two upstream sources, both pinned so the table is reproducible:

  * LLVM's StdSymbolMap.inc / StdSpecialSymbolMap.inc -- the symbol -> header
    table clang/tools/include-mapping/gen_std.py extracts from the cppreference
    offline HTML book ("Defined in header <x>"), with the multi-header cases
    hand-curated in header-preference order.
  * The C++ working draft -- the mandated include lists that open each library
    header's synopsis ([ranges.syn] opens with `#include <iterator>`).

Mandated lists only grow between standards, so a draft newer than melon's C++23
floor can only make the check more permissive, never stricter.
"""
import json
import re
import sys
import urllib.request

LLVM_TAG = "llvmorg-18.1.8"
DRAFT_COMMIT = "9482753e7e0325d86b6b9ff3457dbdfbc7790006"

LLVM_RAW = ("https://raw.githubusercontent.com/llvm/llvm-project/" + LLVM_TAG +
            "/clang/lib/Tooling/Inclusions/Stdlib/")
DRAFT_RAW = ("https://raw.githubusercontent.com/cplusplus/draft/" +
             DRAFT_COMMIT + "/source/")
DRAFT_API = ("https://api.github.com/repos/cplusplus/draft/contents/source?ref="
             + DRAFT_COMMIT)

SYMBOL_RE = re.compile(r"^SYMBOL\((\w+),\s*([\w:]*|None),\s*<([^>]+)>\)")
# [iterator.synopsis] spells its title "\tcode{<iterator>}\ synopsis"; the
# escaped space is not optional in the pattern or that header drops out.
SECTION_RE = re.compile(
    r"\\rSec\d\[([^\]]+)\]\{Header \\tcode\{<([^>]+)>\}\\?\s*synopsis\}")
ANY_SECTION_RE = re.compile(r"\\rSec\d\[")
INCLUDE_RE = re.compile(r"^#include <([^>]+)>")


def fetch(url):
    with urllib.request.urlopen(url, timeout=120) as r:
        return r.read().decode("utf-8", "replace")


def symbol_headers():
    """Qualified name -> providing headers, in the upstream preference order."""
    table = {}
    for name in ("StdSymbolMap.inc", "StdSpecialSymbolMap.inc"):
        for line in fetch(LLVM_RAW + name).splitlines():
            mo = SYMBOL_RE.match(line)
            if mo is None:
                continue
            symbol, namespace, header = mo.groups()
            # Unqualified C names (namespace "None") would have to be matched as
            # bare `min`, `abs`, `size_t`; every such match is a coin flip
            # against a local identifier, so the table carries std:: only.
            if namespace in ("None", ""):
                continue
            headers = table.setdefault(namespace + symbol, [])
            if header not in headers:
                headers.append(header)
    return table


def mandated_includes():
    """Header -> the includes its synopsis mandates."""
    listing = json.loads(fetch(DRAFT_API))
    table = {}
    for entry in listing:
        if not entry["name"].endswith(".tex"):
            continue
        lines = fetch(DRAFT_RAW + entry["name"]).splitlines()
        for i, line in enumerate(lines):
            mo = SECTION_RE.search(line)
            if mo is None:
                continue
            header, j = mo.group(2), i + 1
            while j < len(lines) and not lines[j].startswith(r"\begin{codeblock}"):
                # An empty synopsis (<iso646.h>) has no codeblock at all; without
                # this the scan runs on and adopts the next section's includes.
                if ANY_SECTION_RE.search(lines[j]):
                    j = None
                    break
                j += 1
            if j is None or j >= len(lines):
                continue
            includes = []
            for line in lines[j + 1:]:
                if line.startswith(r"\end{codeblock}"):
                    break
                mo = INCLUDE_RE.match(line)
                if mo is not None:
                    includes.append(mo.group(1))
            if includes:
                table[header] = includes
    return table


def main():
    symbols, mandated = symbol_headers(), mandated_includes()
    out = [
        "# Generated by misc/tools/gen_std_include_table.py -- do not edit.",
        "# symbol -> providing headers, from LLVM " + LLVM_TAG + "'s",
        "# StdSymbolMap.inc (Apache-2.0 WITH LLVM-exception), itself derived",
        "# from cppreference.com (CC-BY-SA 3.0).",
        "# mandated -> the include lists opening each library header synopsis,",
        "# from cplusplus/draft " + DRAFT_COMMIT[:12] + ".",
        "",
        "[mandated]",
    ]
    out += [k + " " + " ".join(v) for k, v in sorted(mandated.items())]
    out += ["", "[symbols]"]
    out += [k + " " + " ".join(v) for k, v in sorted(symbols.items())]
    sys.stdout.write("\n".join(out) + "\n")


main()
